data_samples = {"2018": {"tauTau":["Tau__Run2018A",
                                   "Tau__Run2018B",
                                   "Tau__Run2018C",
                                   "Tau__Run2018D",],
                       "muTau": ["SingleMuon__Run2018A",
                                 "SingleMuon__Run2018B",
                                 "SingleMuon__Run2018C",
                                 "SingleMuon__Run2018D",],
                       "eTau": ["EGamma__Run2018A",
                                "EGamma__Run2018B",
                                "EGamma__Run2018C",
                                "EGamma__Run2018D",]
                         },
                "2017":{"tauTau":["SKIM_Tau_Run2017B",
                                "SKIM_Tau_Run2017C",
                                "SKIM_Tau_Run2017D",
                                "SKIM_Tau_Run2017E",
                                "SKIM_Tau_Run2017F",],
                      "muTau": ["SKIM_SingleMuon_Run2017B",
                                  "SKIM_SingleMuon_Run2017C",
                                  "SKIM_SingleMuon_Run2017D",
                                  "SKIM_SingleMuon_Run2017E",
                                  "SKIM_SingleMuon_Run2017F",],
                      "eTau": ["SKIM_EGamma_Run2017B",
                               "SKIM_EGamma_Run2017C",
                               "SKIM_EGamma_Run2017D",
                               "SKIM_EGamma_Run2017E",
                               "SKIM_EGamma_Run2017F",]
                     },
                "2016":{"tauTau":["SKIM_Tau_Run2016F",
                                "SKIM_Tau_Run2016G",
                                "SKIM_Tau_Run2016H",],
                      "muTau": ["SKIM_Mu_Run2016F",
                                  "SKIM_Mu_Run2016G",
                                  "SKIM_Mu_Run2016H",],
                      "eTau": ["SKIM_Ele_Run2016F",
                               "SKIM_Ele_Run2016G",
                               "SKIM_Ele_Run2016H"]
                     },
                "2016APV":{"muTau": ["SKIM_Tau_2016B",
                                "SKIM_Tau_2016C",
                                "SKIM_Tau_2016D",
                                "SKIM_Tau_2016E",
                                "SKIM_Tau_2016F",],
                      "muTau": ["SKIM_Mu_2016B",
                                "SKIM_Mu_2016C",
                                "SKIM_Mu_2016D",
                                "SKIM_Mu_2016E",
                                "SKIM_Mu_2016F",],
                      "eTau": ["SKIM_Ele_2016B",
                               "SKIM_Ele_2016C",
                               "SKIM_Ele_2016D",
                               "SKIM_Ele_2016E",
                               "SKIM_Ele_2016F"]
                     }
                }